version: '3.9'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootroot
      POSTGRES_DB: crm_db
    container_name: nest_db
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5433'
  api:
    container_name: slp_crm
    build: .
    ports:
      - '5000:5000'
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:rootroot@db:5432/crm_db?schema=public
    depends_on:
      - db
    restart: unless-stopped
    command: >
      sh -c "npx prisma db push &&
        yarn start:prod"
    volumes:
      - ./uploads:/app/uploads

  frontend:
    container_name: front
    build: ../crm_project_front
    restart: unless-stopped
    ports:
      - '80:80'
    depends_on:
      - api

volumes:
  pgdata:
